package v201

// transaction.go — TransactionEvent handler (README 4.3.5).
// OCPP 2.0.1 replaces StartTransaction/StopTransaction/MeterValues with a
// single TransactionEvent message carrying eventType Started/Updated/Ended.
//
// transactionId is generated by the DEVICE (string). Because different charge
// points may report the same transactionId, a transaction is bound by
// chargePointId + evseId + connectorId + transactionId (table transaction_201).
//
// Every TransactionEvent is recorded in transaction_event_201. Events with
// triggerReason MeterValueClock / MeterValuePeriodic are only written to the
// event log; the others are shown in the frontend (README 4.3.5).

import (
	"encoding/json"
	"time"

	"github.com/yourorg/csms-backend/internal/model"
	"github.com/yourorg/csms-backend/internal/ocppws"
	"github.com/yourorg/csms-backend/internal/repository"
)

// ─── TransactionEvent ────────────────────────────────────────────────────────
// Schema: TransactionEventRequest.json / TransactionEventResponse.json

type transactionEventReq struct {
	EventType       string `json:"eventType"`
	Timestamp       string `json:"timestamp"`
	TriggerReason   string `json:"triggerReason"`
	SeqNo           int    `json:"seqNo"`
	Offline         *bool  `json:"offline"`
	TransactionInfo struct {
		TransactionID string `json:"transactionId"`
		ChargingState string `json:"chargingState"`
		StoppedReason string `json:"stoppedReason"`
	} `json:"transactionInfo"`
	Evse *struct {
		ID          int  `json:"id"`
		ConnectorID *int `json:"connectorId"`
	} `json:"evse"`
	IDToken *struct {
		IDToken string `json:"idToken"`
		Type    string `json:"type"`
	} `json:"idToken"`
	MeterValue []meterValueType `json:"meterValue"`
}

type meterValueType struct {
	Timestamp    string             `json:"timestamp"`
	SampledValue []sampledValueType `json:"sampledValue"`
}

type sampledValueType struct {
	Value     float64 `json:"value"`
	Measurand string  `json:"measurand"`
}

// isMeterEvent reports whether this event was triggered by meter sampling
// (TriggerReasonEnumType MeterValueClock / MeterValuePeriodic).
func isMeterEvent(triggerReason string) bool {
	return triggerReason == "MeterValueClock" || triggerReason == "MeterValuePeriodic"
}

func handleTransactionEvent(dc *ocppws.DeviceConnection, call *ocppws.CallMessage, eventCh chan<- *model.Event) {
	var req transactionEventReq
	_ = json.Unmarshal(call.Payload, &req)

	evseID := 1
	connectorID := 1
	if req.Evse != nil {
		if req.Evse.ID > 0 {
			evseID = req.Evse.ID
		}
		if req.Evse.ConnectorID != nil {
			connectorID = *req.Evse.ConnectorID
		}
	}
	idTag := ""
	if req.IDToken != nil {
		idTag = req.IDToken.IDToken
	}
	txID := req.TransactionInfo.TransactionID

	eventTime := time.Now().UTC()
	if t, err := time.Parse(time.RFC3339, req.Timestamp); err == nil {
		eventTime = t
	}

	// 1. Record every TransactionEvent (README 4.3.5)
	payloadJSON, _ := json.Marshal(req)
	_ = repository.InsertTransactionEvent201(&model.TransactionEvent201{
		TenantID:      dc.TenantID,
		ChargePointID: dc.DeviceName,
		TransactionID: txID,
		EvseID:        evseID,
		ConnectorID:   connectorID,
		EventType:     req.EventType,
		TriggerReason: req.TriggerReason,
		SeqNo:         req.SeqNo,
		Payload:       string(payloadJSON),
	})

	// 2. Meter-sampling events go to the log only
	if isMeterEvent(req.TriggerReason) {
		sendResult(dc, call.MsgID, struct{}{})
		pushEvent(eventCh, dc.TenantID, "info", dc.DeviceName,
			"TransactionEvent "+req.EventType+" trigger="+req.TriggerReason+
				" txId="+txID+" evse="+itoa(evseID)+" connector="+itoa(connectorID)+" (log only)")
		return
	}

	// 3. Update transaction_201 state
	switch req.EventType {
	case "Started":
		handleTxStarted(dc, call, eventCh, &req, evseID, connectorID, idTag, txID, eventTime)
	case "Ended":
		handleTxEnded(dc, call, eventCh, &req, evseID, connectorID, txID, eventTime)
	case "Updated":
		handleTxUpdated(dc, call, eventCh, &req, evseID, connectorID, txID)
	default:
		// Unknown eventType — acknowledge without side effects
		sendResult(dc, call.MsgID, struct{}{})
	}
}

// handleTxStarted creates (or refreshes) the transaction row keyed by
// chargePointId+evseId+connectorId+transactionId (device-generated txid).
func handleTxStarted(dc *ocppws.DeviceConnection, call *ocppws.CallMessage, eventCh chan<- *model.Event,
	req *transactionEventReq, evseID, connectorID int, idTag, txID string, eventTime time.Time) {

	tx := &model.Transaction201{
		TransactionID: txID,
		ChargePointID: dc.DeviceName,
		EvseID:        evseID,
		ConnectorID:   connectorID,
		TenantID:      dc.TenantID,
		IDTag:         idTag,
		StartTime:     eventTime,
		StartMeter:    firstMeterValue(req),
		Active:        true,
	}
	_ = repository.UpsertTransaction201(tx)

	sendResult(dc, call.MsgID, struct{}{})

	pushEvent(eventCh, dc.TenantID, "info", dc.DeviceName,
		"TransactionEvent Started txId="+txID+" evse="+itoa(evseID)+
			" connector="+itoa(connectorID)+" idTag="+idTag)
}

// handleTxUpdated refreshes meter values sampled during the transaction.
func handleTxUpdated(dc *ocppws.DeviceConnection, call *ocppws.CallMessage, eventCh chan<- *model.Event,
	req *transactionEventReq, evseID, connectorID int, txID string) {

	if len(req.MeterValue) > 0 {
		last := lastMeterValue(req)
		if last > 0 {
			_, _ = repository.DB.Exec(
				`UPDATE transaction_201 SET stop_meter=? WHERE charge_point_id=? AND evse_id=? AND connector_id=? AND transaction_id=? AND tenant_id=? AND active=1`,
				last, dc.DeviceName, evseID, connectorID, txID, dc.TenantID)
		}
	}

	sendResult(dc, call.MsgID, struct{}{})

	pushEvent(eventCh, dc.TenantID, "info", dc.DeviceName,
		"TransactionEvent Updated txId="+txID+" evse="+itoa(evseID)+
			" connector="+itoa(connectorID)+" reason="+req.TriggerReason)
}

// handleTxEnded closes the transaction bound by the device-generated txid.
func handleTxEnded(dc *ocppws.DeviceConnection, call *ocppws.CallMessage, eventCh chan<- *model.Event,
	req *transactionEventReq, evseID, connectorID int, txID string, eventTime time.Time) {

	_ = repository.CloseTransaction201(dc.DeviceName, evseID, connectorID, txID, dc.TenantID,
		eventTime, lastMeterValue(req), req.TransactionInfo.StoppedReason)

	sendResult(dc, call.MsgID, struct{}{})

	pushEvent(eventCh, dc.TenantID, "info", dc.DeviceName,
		"TransactionEvent Ended txId="+txID+" evse="+itoa(evseID)+
			" connector="+itoa(connectorID)+" reason="+req.TransactionInfo.StoppedReason)
}

// firstMeterValue returns the first sampled value with measurand
// Energy.Active.Import.Register (fallback: first sampled value overall).
func firstMeterValue(req *transactionEventReq) float64 {
	for _, mv := range req.MeterValue {
		for _, sv := range mv.SampledValue {
			if sv.Measurand == "Energy.Active.Import.Register" || sv.Measurand == "" {
				return sv.Value
			}
		}
	}
	return lastMeterValue(req)
}

// lastMeterValue returns the last sampled value reported in this event.
func lastMeterValue(req *transactionEventReq) float64 {
	var v float64
	for _, mv := range req.MeterValue {
		for _, sv := range mv.SampledValue {
			v = sv.Value
		}
	}
	return v
}
