-- 002_ocpp201_features.sql
-- Implements the README additions:
--   2.3.1   overview per-connector / per-EVSE status + bootreason
--   2.3.4.3 device protocol-dependent topology (connectorNo / evseNo)
--   2.3.4.4 idtag.type (IdTokenEnumType for OCPP 2.x)
--   4.3.2   bootreason stored in DB
--   4.3.5 / 5.3  OCPP 2.0.1 transaction tables (device-generated txid,
--          keyed by device+evse+connector+transactionId) + raw event log
--
-- Idempotent: every statement is guarded via information_schema.
USE `db-saas-ocpp-dev`;

-- ─── transaction: add missing updated_at (used by StopTransaction) ─────────
SET @sql = (SELECT IF(
  (SELECT COUNT(*) FROM information_schema.columns
   WHERE table_schema='db-saas-ocpp-dev' AND table_name='transaction' AND column_name='updated_at') = 0,
  'ALTER TABLE transaction ADD COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP',
  'SELECT 1'));
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

-- ─── device: topology + boot reason ─────────────────────────────────────────
SET @sql = (SELECT IF(
  (SELECT COUNT(*) FROM information_schema.columns
   WHERE table_schema='db-saas-ocpp-dev' AND table_name='device' AND column_name='connector_no') = 0,
  'ALTER TABLE device ADD COLUMN connector_no INT NOT NULL DEFAULT 2 COMMENT ''connector count (OCPP16) / per-EVSE connector count (OCPP201)'' AFTER heartbeat_interval',
  'SELECT 1'));
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

SET @sql = (SELECT IF(
  (SELECT COUNT(*) FROM information_schema.columns
   WHERE table_schema='db-saas-ocpp-dev' AND table_name='device' AND column_name='evse_no') = 0,
  'ALTER TABLE device ADD COLUMN evse_no INT NOT NULL DEFAULT 0 COMMENT ''EVSE count, OCPP201/OCPP21 only (0 = N/A)'' AFTER connector_no',
  'SELECT 1'));
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

SET @sql = (SELECT IF(
  (SELECT COUNT(*) FROM information_schema.columns
   WHERE table_schema='db-saas-ocpp-dev' AND table_name='device' AND column_name='boot_reason') = 0,
  'ALTER TABLE device ADD COLUMN boot_reason VARCHAR(64) NOT NULL DEFAULT '''' COMMENT ''last BootNotification.reason (OCPP201)'' AFTER status',
  'SELECT 1'));
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

-- ─── idtag: type (IdTokenEnumType) ──────────────────────────────────────────
SET @sql = (SELECT IF(
  (SELECT COUNT(*) FROM information_schema.columns
   WHERE table_schema='db-saas-ocpp-dev' AND table_name='idtag' AND column_name='type') = 0,
  'ALTER TABLE idtag ADD COLUMN type VARCHAR(32) NOT NULL DEFAULT ''ISO14443'' COMMENT ''IdTokenEnumType: Central,eMAID,ISO14443,ISO15693,KeyCode,Local,MacAddress,NoAuthorization'' AFTER parent_tag_id',
  'SELECT 1'));
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

-- ─── connector_status: per-EVSE/per-connector live status (2.3.1) ───────────
-- v16:   evse_id = 0, connector_id = 1..device.connector_no
-- v201:  evse_id = 1..device.evse_no, connector_id = 1..device.connector_no
CREATE TABLE IF NOT EXISTS `connector_status` (
  `id`           BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  `device_id`    VARCHAR(36)  NOT NULL,
  `evse_id`      INT          NOT NULL DEFAULT 0,
  `connector_id` INT          NOT NULL DEFAULT 1,
  `status`       VARCHAR(32)  NOT NULL DEFAULT 'Unavailable',
  `updated_at`   DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_cs_device (`device_id`, `evse_id`, `connector_id`),
  INDEX idx_cs_device (`device_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ─── 5.3 transaction split: OCPP 2.0.1 table ───────────────────────────────
-- transactionId is generated by the device (string). Binding key:
-- device + evseId + connectorId + transactionId (README 4.3.5).
CREATE TABLE IF NOT EXISTS `transaction_201` (
  `id`              BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  `transaction_id`  VARCHAR(64)  NOT NULL,
  `charge_point_id` VARCHAR(64)  NOT NULL,
  `evse_id`         INT          NOT NULL DEFAULT 1,
  `connector_id`    INT          NOT NULL DEFAULT 1,
  `tenant_id`       VARCHAR(36)  NOT NULL,
  `id_tag`          VARCHAR(64)  NOT NULL DEFAULT '',
  `start_time`      DATETIME     NOT NULL,
  `stop_time`       DATETIME     NULL,
  `start_meter`     DOUBLE       NOT NULL DEFAULT 0,
  `stop_meter`      DOUBLE       NULL,
  `stop_reason`     VARCHAR(64)  NOT NULL DEFAULT '',
  `active`          TINYINT(1)   NOT NULL DEFAULT 1,
  UNIQUE KEY uq_tx201 (`transaction_id`, `charge_point_id`, `evse_id`, `connector_id`, `tenant_id`),
  INDEX idx_tx201_cp     (`charge_point_id`),
  INDEX idx_tx201_active (`active`),
  INDEX idx_tx201_tenant (`tenant_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ─── transaction_event_201: raw TransactionEvent record (4.3.5) ────────────
-- Every TransactionEvent message is stored here. Events triggered by
-- MeterValueClock / MeterValuePeriodic are additionally written to the event
-- log only; the rest are shown in the frontend.
CREATE TABLE IF NOT EXISTS `transaction_event_201` (
  `id`              BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  `tenant_id`       VARCHAR(36)  NOT NULL,
  `charge_point_id` VARCHAR(64)  NOT NULL,
  `transaction_id`  VARCHAR(64)  NOT NULL DEFAULT '',
  `evse_id`         INT          NOT NULL DEFAULT 1,
  `connector_id`    INT          NOT NULL DEFAULT 1,
  `event_type`      VARCHAR(16)  NOT NULL,            -- Started | Updated | Ended
  `trigger_reason`  VARCHAR(32)  NOT NULL DEFAULT '',
  `seq_no`          INT          NOT NULL DEFAULT 0,
  `payload`         JSON         NOT NULL,            -- full TransactionEventRequest
  `created_at`      DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_txe201_cp    (`charge_point_id`, `created_at`),
  INDEX idx_txe201_tx    (`charge_point_id`, `evse_id`, `connector_id`, `transaction_id`),
  INDEX idx_txe201_tenant (`tenant_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ─── cert_serial: dedupe + unique key on (tenant_id, cert_type) ────────────
-- 001_init.sql only created an index, so INSERT IGNORE accumulated duplicate
-- rows. Keep the highest serial per (tenant, cert_type), then add the key.
DELETE c1 FROM cert_serial c1
  JOIN cert_serial c2
    ON c2.tenant_id = c1.tenant_id AND c2.cert_type = c1.cert_type
   AND (c2.serial_no > c1.serial_no OR (c2.serial_no = c1.serial_no AND c2.id < c1.id));

SET @sql = (SELECT IF(
  (SELECT COUNT(*) FROM information_schema.statistics
   WHERE table_schema='db-saas-ocpp-dev' AND table_name='cert_serial' AND index_name='uq_cs_tenant_type') = 0,
  'ALTER TABLE cert_serial ADD UNIQUE KEY uq_cs_tenant_type (tenant_id, cert_type)',
  'SELECT 1'));
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
